name: 'Discord Notification'
on:
  release:
    types:
      - published

jobs:
  NotifyDiscord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord Server
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          color: '#651FFF'
          details: '🚀 A new release has been published!\n**Release Name:** ${{ github.event.release.name }}\n**Version:** ${{ github.event.release.tag_name }}\n**Details:**\n${{ github.event.release.body }}'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
