name: 'Discord Notification'
on:
  push:
    branches:
      - main

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord Server
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
