name: Publish Canary

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
    branches:
      - canary

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.11

      - name: Install required Node.js version
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: PNPM install
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): changesets versioning & publication'
          createGithubReleases: true
          publish: pnpm run publish:canary
          title: 'Changesets: Versioning & Publication'
          version: pnpm exec changeset version --snapshot canary --tag canary
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
